# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: volume_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'volume_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13volume_server.proto\x12\x10volume_server_pb\"\x07\n\x05\x45mpty\"-\n\x18VacuumVolumeCheckRequest\x12\x11\n\tvolume_id\x18\x01 \x01(\r\"2\n\x19VacuumVolumeCheckResponse\x12\x15\n\rgarbage_ratio\x18\x01 \x01(\x01\"D\n\x1aVacuumVolumeCompactRequest\x12\x11\n\tvolume_id\x18\x01 \x01(\r\x12\x13\n\x0bpreallocate\x18\x02 \x01(\x03\"K\n\x1bVacuumVolumeCompactResponse\x12\x17\n\x0fprocessed_bytes\x18\x01 \x01(\x03\x12\x13\n\x0bload_avg_1m\x18\x02 \x01(\x02\".\n\x19VacuumVolumeCommitRequest\x12\x11\n\tvolume_id\x18\x01 \x01(\r\"G\n\x1aVacuumVolumeCommitResponse\x12\x14\n\x0cis_read_only\x18\x01 \x01(\x08\x12\x13\n\x0bvolume_size\x18\x02 \x01(\x04\"/\n\x1aVacuumVolumeCleanupRequest\x12\x11\n\tvolume_id\x18\x01 \x01(\r\"\x1d\n\x1bVacuumVolumeCleanupResponse2\xdf\x03\n\x0cVolumeServer\x12n\n\x11VacuumVolumeCheck\x12*.volume_server_pb.VacuumVolumeCheckRequest\x1a+.volume_server_pb.VacuumVolumeCheckResponse\"\x00\x12v\n\x13VacuumVolumeCompact\x12,.volume_server_pb.VacuumVolumeCompactRequest\x1a-.volume_server_pb.VacuumVolumeCompactResponse\"\x00\x30\x01\x12q\n\x12VacuumVolumeCommit\x12+.volume_server_pb.VacuumVolumeCommitRequest\x1a,.volume_server_pb.VacuumVolumeCommitResponse\"\x00\x12t\n\x13VacuumVolumeCleanup\x12,.volume_server_pb.VacuumVolumeCleanupRequest\x1a-.volume_server_pb.VacuumVolumeCleanupResponse\"\x00\x42\x39Z7github.com/seaweedfs/seaweedfs/weed/pb/volume_server_pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'volume_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/seaweedfs/seaweedfs/weed/pb/volume_server_pb'
  _globals['_EMPTY']._serialized_start=41
  _globals['_EMPTY']._serialized_end=48
  _globals['_VACUUMVOLUMECHECKREQUEST']._serialized_start=50
  _globals['_VACUUMVOLUMECHECKREQUEST']._serialized_end=95
  _globals['_VACUUMVOLUMECHECKRESPONSE']._serialized_start=97
  _globals['_VACUUMVOLUMECHECKRESPONSE']._serialized_end=147
  _globals['_VACUUMVOLUMECOMPACTREQUEST']._serialized_start=149
  _globals['_VACUUMVOLUMECOMPACTREQUEST']._serialized_end=217
  _globals['_VACUUMVOLUMECOMPACTRESPONSE']._serialized_start=219
  _globals['_VACUUMVOLUMECOMPACTRESPONSE']._serialized_end=294
  _globals['_VACUUMVOLUMECOMMITREQUEST']._serialized_start=296
  _globals['_VACUUMVOLUMECOMMITREQUEST']._serialized_end=342
  _globals['_VACUUMVOLUMECOMMITRESPONSE']._serialized_start=344
  _globals['_VACUUMVOLUMECOMMITRESPONSE']._serialized_end=415
  _globals['_VACUUMVOLUMECLEANUPREQUEST']._serialized_start=417
  _globals['_VACUUMVOLUMECLEANUPREQUEST']._serialized_end=464
  _globals['_VACUUMVOLUMECLEANUPRESPONSE']._serialized_start=466
  _globals['_VACUUMVOLUMECLEANUPRESPONSE']._serialized_end=495
  _globals['_VOLUMESERVER']._serialized_start=498
  _globals['_VOLUMESERVER']._serialized_end=977
# @@protoc_insertion_point(module_scope)
