# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import volume_server_pb2 as volume__server__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in volume_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VolumeServerStub(object):
    """////////////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VacuumVolumeCheck = channel.unary_unary(
                '/volume_server_pb.VolumeServer/VacuumVolumeCheck',
                request_serializer=volume__server__pb2.VacuumVolumeCheckRequest.SerializeToString,
                response_deserializer=volume__server__pb2.VacuumVolumeCheckResponse.FromString,
                _registered_method=True)
        self.VacuumVolumeCompact = channel.unary_stream(
                '/volume_server_pb.VolumeServer/VacuumVolumeCompact',
                request_serializer=volume__server__pb2.VacuumVolumeCompactRequest.SerializeToString,
                response_deserializer=volume__server__pb2.VacuumVolumeCompactResponse.FromString,
                _registered_method=True)
        self.VacuumVolumeCommit = channel.unary_unary(
                '/volume_server_pb.VolumeServer/VacuumVolumeCommit',
                request_serializer=volume__server__pb2.VacuumVolumeCommitRequest.SerializeToString,
                response_deserializer=volume__server__pb2.VacuumVolumeCommitResponse.FromString,
                _registered_method=True)
        self.VacuumVolumeCleanup = channel.unary_unary(
                '/volume_server_pb.VolumeServer/VacuumVolumeCleanup',
                request_serializer=volume__server__pb2.VacuumVolumeCleanupRequest.SerializeToString,
                response_deserializer=volume__server__pb2.VacuumVolumeCleanupResponse.FromString,
                _registered_method=True)


class VolumeServerServicer(object):
    """////////////////////////////////////////////////

    """

    def VacuumVolumeCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VacuumVolumeCompact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VacuumVolumeCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VacuumVolumeCleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VolumeServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VacuumVolumeCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.VacuumVolumeCheck,
                    request_deserializer=volume__server__pb2.VacuumVolumeCheckRequest.FromString,
                    response_serializer=volume__server__pb2.VacuumVolumeCheckResponse.SerializeToString,
            ),
            'VacuumVolumeCompact': grpc.unary_stream_rpc_method_handler(
                    servicer.VacuumVolumeCompact,
                    request_deserializer=volume__server__pb2.VacuumVolumeCompactRequest.FromString,
                    response_serializer=volume__server__pb2.VacuumVolumeCompactResponse.SerializeToString,
            ),
            'VacuumVolumeCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.VacuumVolumeCommit,
                    request_deserializer=volume__server__pb2.VacuumVolumeCommitRequest.FromString,
                    response_serializer=volume__server__pb2.VacuumVolumeCommitResponse.SerializeToString,
            ),
            'VacuumVolumeCleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.VacuumVolumeCleanup,
                    request_deserializer=volume__server__pb2.VacuumVolumeCleanupRequest.FromString,
                    response_serializer=volume__server__pb2.VacuumVolumeCleanupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'volume_server_pb.VolumeServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('volume_server_pb.VolumeServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VolumeServer(object):
    """////////////////////////////////////////////////

    """

    @staticmethod
    def VacuumVolumeCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/volume_server_pb.VolumeServer/VacuumVolumeCheck',
            volume__server__pb2.VacuumVolumeCheckRequest.SerializeToString,
            volume__server__pb2.VacuumVolumeCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VacuumVolumeCompact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/volume_server_pb.VolumeServer/VacuumVolumeCompact',
            volume__server__pb2.VacuumVolumeCompactRequest.SerializeToString,
            volume__server__pb2.VacuumVolumeCompactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VacuumVolumeCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/volume_server_pb.VolumeServer/VacuumVolumeCommit',
            volume__server__pb2.VacuumVolumeCommitRequest.SerializeToString,
            volume__server__pb2.VacuumVolumeCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VacuumVolumeCleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/volume_server_pb.VolumeServer/VacuumVolumeCleanup',
            volume__server__pb2.VacuumVolumeCleanupRequest.SerializeToString,
            volume__server__pb2.VacuumVolumeCleanupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
